In [1]:
import  pandas as pd
pd.__version__

'3.0.3'

Series= 1 list ;
Dataframe = full table.

START PANDAS SERIES

In [2]:
sales=pd.Series([5,6,2,3,5,0,9])
print(sales)
#to create and print a series use the above

0    5
1    6
2    2
3    3
4    5
5    0
6    9
dtype: int64

In [3]:
sales[1]
#to access a particular variable at a particular index we can call it like this in the series

np.int64(6)

In [4]:
sales[0:2]
#data slicing refers to the slicing or retreiving certain part of the data ranging from 0th index position to <nth position as pre4sented in the above position

0    5
1    6
dtype: int64

In [5]:
#ATTRIBUTES USED TO FIND INFORMATION ABOUT THE SPECIFIC SERIES
sales.index #.index is used here to provide the specific index values implemented/used by the series
sales.values #.values is used here to provide the specific values which the series conatins
sales.dtype #.dtype is used here to know what the specific datatype of the values of the series contains

dtype('int64')

METHODS USED TO SEE DATA IN SERIES

In [6]:
#1.head(n)
sales.head(1)
#a .head() method is used to display the "HEAD" ie the starting (0th position) to the nth position(here n is the no. of elements you want to see from the start ie its the limit to where you want to see)

0    5
dtype: int64

In [7]:
#2 .tail(n)
sales.tail(1)
#just think the opposite of tail i.e. starting from bottom ,rest properties kinda remain same(0th to n changes to the ending point to the upper levels)

6    9
dtype: int64

In [8]:
#3.sort_values()
sales.sort_values()
#if you think the data is not sorted use this

5    0
2    2
3    3
0    5
4    5
1    6
6    9
dtype: int64

In [9]:
#4.count()
sales.count()
#counts number of elements in this series

np.int64(7)

In [10]:
#5.isnull()
sales.isnull()
#used to see in data where the positions are blank i.e. null

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [11]:
#6.notnull()
sales.notnull()
#used to see in data where the positions are not blank ; hence "notnull"

0    True
1    True
2    True
3    True
4    True
5    True
6    True
dtype: bool

In [12]:
#you can perform several mathematical operations like +,-,*,// and **
sales//2

0    2
1    3
2    1
3    1
4    2
5    0
6    4
dtype: int64

In [13]:
sales_gayab=pd.Series([2,None,5,9,None,3,6])
#new series to check for null manipulation in series

In [14]:
sales_gayab.isnull()

0    False
1     True
2    False
3    False
4     True
5    False
6    False
dtype: bool

In [15]:
#to solve the null issue we use 
sales_gayab = sales_gayab.fillna(0)
#this fills the null value with 0

In [16]:
sales_gayab

0    2.0
1    0.0
2    5.0
3    9.0
4    0.0
5    3.0
6    6.0
dtype: float64

START PANDAS DATAFRAME

In [17]:
data = pd.DataFrame({'Name':['Anna','Ben'],'Lemonades':[2,3]})
data

   Name  Lemonades
0  Anna          2
1   Ben          3

In [18]:
s1=pd.Series(data=[1,2,3,4,5])
s2=pd.Series(data=[10,20,30,40,50])
si= pd.Series(data=[100,200,300,400,500],index=list('abcde'))
data = pd.DataFrame({'C1':s1,'C2':s2})

In [19]:
data

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [20]:
s1.shape

(5,)

In [21]:
data.shape

(5, 2)

In [22]:
data.columns

Index(['C1', 'C2'], dtype='str')

In [23]:
data.dtypes

C1    int64
C2    int64
dtype: object

ACCESSING DATA IN DATAFRAME USING LOC AND ILOC

In [24]:
#using loc for accessing data
data.loc[1,'C1']#loc uses labels

np.int64(2)

In [25]:
#using iloc for accessing data
data.iloc[3,0]#iloc access data by index

np.int64(4)

In [26]:
data.head()

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [27]:
data.tail()

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [28]:
data.count()

C1    5
C2    5
dtype: int64

In [29]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      5 non-null      int64
 1   C2      5 non-null      int64
dtypes: int64(2)
memory usage: 212.0 bytes

In [30]:
data.describe()

             C1         C2
count  5.000000   5.000000
mean   3.000000  30.000000
std    1.581139  15.811388
min    1.000000  10.000000
25%    2.000000  20.000000
50%    3.000000  30.000000
75%    4.000000  40.000000
max    5.000000  50.000000

FILTERING IN DF

In [31]:
data[data['C1']>=2]

   C1  C2
1   2  20
2   3  30
3   4  40
4   5  50

ADDING,UPDATING and DELETING

In [32]:
data['TIPS']=[1,2,3,4,8]

In [33]:
print(data)

   C1  C2  TIPS
0   1  10     1
1   2  20     2
2   3  30     3
3   4  40     4
4   5  50     8

In [34]:
del data['TIPS'] # or we can use data=data.drop(columns=['TIPS'])
print(data)

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [35]:
data.loc[data['C1']==2]=10
print(data.head())

   C1  C2
0   1  10
1  10  10
2   3  30
3   4  40
4   5  50

In [38]:
data=data.rename(columns={'C1':'Column1'})
data =data.rename(index={2:'Row2'})
print(data)

      Column1  C2
0           1  10
1          10  10
Row2        3  30
3           4  40
4           5  50